# Generated by Django 4.1 on 2023-04-10 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='api.card')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatronController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrons', models.ManyToManyField(to='api.patron')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('observers', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patroncontroller')),
                ('patrons', models.ManyToManyField(blank=True, to='api.patron')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokensJSON', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VictoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('cardstack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.cardstack')),
            ],
            bases=('api.cardstack',),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('cardstack_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.cardstack')),
            ],
            bases=('api.cardstack',),
        ),
        migrations.CreateModel(
            name='ShopController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranks', models.ManyToManyField(to='api.rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='api.player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='tokens',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tokenarray'),
        ),
        migrations.AddField(
            model_name='player',
            name='victoryPoints',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.victorypoint'),
        ),
        migrations.AddField(
            model_name='patron',
            name='requirements',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tokenarray'),
        ),
        migrations.AddField(
            model_name='patron',
            name='victoryPoints',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.victorypoint'),
        ),
        migrations.CreateModel(
            name='GameManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankController', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bankcontroller')),
                ('patronController', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.patroncontroller')),
                ('playerController', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.playercontroller')),
                ('shopController', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shopcontroller')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='bonus',
            field=models.ManyToManyField(related_name='bonus', to='api.tokenarray'),
        ),
        migrations.AddField(
            model_name='card',
            name='price',
            field=models.ManyToManyField(related_name='price', to='api.tokenarray'),
        ),
        migrations.AddField(
            model_name='card',
            name='victoryPoint',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.victorypoint'),
        ),
        migrations.AddField(
            model_name='bankcontroller',
            name='bank',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tokenarray'),
        ),
        migrations.AddField(
            model_name='rank',
            name='deck',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deck'),
        ),
        migrations.AddField(
            model_name='rank',
            name='hand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.hand'),
        ),
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hand', to='api.hand'),
        ),
        migrations.AddField(
            model_name='player',
            name='reserved',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserved', to='api.hand'),
        ),
    ]
