# Generated by Django 4.1 on 2023-04-10 16:51

from django.db import migrations

from django.db import migrations

def load_initial_data(apps, schema_editor):
    apps.get_model('api', 'GameManager').objects.create(
        bankController = apps.get_model('api', 'BankController').objects.create(),
        patronController =apps.get_model('api', 'PatronController').objects.create(),
        playerController =apps.get_model('api', 'PlayerController').objects.create(),
        shopController =apps.get_model('api', 'ShopController').objects.create()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
       migrations.RunPython(load_initial_data),
    ]
