@startuml Sequence Diagram
title User buy from shop
scale 1

boundary Front
control GameManager
entity PlayerController
entity ShopController
entity BankController


Front -> GameManager : PlayerId Buy CardId
activate GameManager

GameManager -> PlayerController : BuyShopCard\n(PlayerId, CardId)
activate PlayerController



PlayerController -> ShopController : GetCardPrice\n(CardId)
activate ShopController
PlayerController <- ShopController : TokenArray
deactivate ShopController

PlayerController -> Player1 : Pay(TokenArray)
activate Player1
PlayerController <-- Player1 : ok
deactivate Player1

PlayerController -> BankController : Deposit(TokenArray)
activate BankController
PlayerController <-- BankController : ok
deactivate BankController

PlayerController -> ShopController : WithdrawCard\n(CardId)
activate ShopController
ShopController --> ShopController : Draw()
PlayerController <- ShopController : Card
deactivate ShopController

PlayerController -> Player1 : DepositCard(Card)
activate Player1
PlayerController <-- Player1 : ok
deactivate Player1



PlayerController --> GameManager : ok
deactivate PlayerController
GameManager --> GameManager : GatherBoardState()
GameManager -> Front : BoardState
deactivate GameManager


@enduml
