@startuml Initialisation
title User takes tokens from the bank
scale 1.5

boundary Front
control GameManager
entity PlayerController
entity BankController


Front -> GameManager : PlayerId Take Tokens
activate GameManager

GameManager -> PlayerController : TakeToken\n(PlayerId, TokenArray)
activate PlayerController

PlayerController -> BankController : Withdraw()
activate BankController
BankController --> PlayerController : ok
deactivate BankController

PlayerController -> Player1 : DepositToken()
activate Player1
PlayerController <-- Player1 : ok
deactivate Player1

PlayerController --> GameManager : Validate
deactivate PlayerController
GameManager --> GameManager : GatherBoardState()
GameManager -> Front : BoardState
deactivate GameManager

@enduml
